name: nested_scroll_views
description: Flutter nested scrolling views.
version: 0.0.8
homepage: https://github.com/hgraceb/nested_scroll_views

environment:
  flutter: '>=3.19.0'
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
